### ISSUE TITLE
NULL

### ISSUE THREAD

**Issue by ghost** [Yaossg/ManaCraft#2]

**Comment by switefaster** [comment]
Actually, this is a simple mod which provides no API. And that means you haven't read codes carefully. You't better make sure before you ask some quetions, and there are, in fact, plenty of manners of asking quetions as https://lug.ustc.edu.cn/wiki/doc/smart-questions listed the most.

**Comment by ghost** [comment]
SF你又拽EN-US

**Comment by ghost** [comment]
切换语言到zh-CN
